name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: docker://ghcr.io/validator/validator:latest
        with:
          args: index.html

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos para publicación
        uses: actions/upload-pages-artifact@v2

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v1
